# Use both URI and individual properties
spring.data.mongodb.uri=mongodb://localhost:27017/invoice_Generator
spring.data.mongodb.database=invoice_Generator
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

server.port=8080

# Disable automatic database creation if you want
spring.data.mongodb.auto-index-creation=true


#cloudinary configuration
cloudinary.cloud_name=dgbiowyya
cloudinary.api_key=Replace with your api_key
cloudinary.api_secret=Replace with your secret




spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=Replace with your username
spring.mail.password=Replace with your pass

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com

spring.mail.protocol=smtp

clerk.issuer=Replace with your issuer
clerk.jwks-url=Replace with your url

spring.security.user.name=dummy
spring.security.user.password=dummy
spring.security.user.enabled=false
